name: "MagicMirror² (develop) and EXT-Website build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install EXT-Website
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Checkout MagicMirror² (develop)
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror
          ref: develop

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout EXT-Website
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/EXT-Website

      - name: Install EXT-Website
        run: npm install
        working-directory: MagicMirror/modules/EXT-Website
        continue-on-error: false
